### ISSUE TITLE
NullPointerException at PageSequenceBuilder2.java:53

### ISSUE THREAD

**Issue by josteinaj** [brailleapps/dotify#209]
Attaching full job log and input XML. The relevant Exception is this:

```
java.lang.RuntimeException: com.xmlcalabash.core.XProcException: java.lang.NullPointerException
    at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:246) ~[na:na]
    at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
    at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:110) ~[na:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
Caused by: com.xmlcalabash.core.XProcException: java.lang.NullPointerException
    at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:143) ~[na:na]
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XChoose.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.extensions.Eval.run(Unknown Source) ~[na:na]
    at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XChoose.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
    ... 3 common frames omitted
Caused by: java.lang.NullPointerException: null
    at org.daisy.dotify.formatter.impl.PageSequenceBuilder2.<init>(PageSequenceBuilder2.java:53) ~[na:na]
    at org.daisy.dotify.formatter.impl.PageStructBuilder.newSequence(PageStructBuilder.java:36) ~[na:na]
    at org.daisy.dotify.formatter.impl.PageStructBuilder.paginate(PageStructBuilder.java:24) ~[na:na]
    at org.daisy.dotify.formatter.impl.FormatterImpl.updateVolumeContents(FormatterImpl.java:262) ~[na:na]
    at org.daisy.dotify.formatter.impl.FormatterImpl.getVolumes(FormatterImpl.java:179) ~[na:na]
    at org.daisy.dotify.formatter.impl.FormatterImpl.write(FormatterImpl.java:131) ~[na:na]
    at org.daisy.dotify.engine.impl.LayoutEngineImpl.convert(LayoutEngineImpl.java:127) ~[na:na]
    at org.daisy.pipeline.braille.dotify.calabash.impl.OBFLToPEFStep.run(OBFLToPEFStep.java:132) ~[na:na]
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XChoose.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.extensions.Eval.run(Unknown Source) ~[na:na]
    at org.daisy.pipeline.braille.common.calabash.impl.PxTransformStep.run(PxTransformStep.java:143) ~[na:na]
    at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XChoose.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source) ~[na:na]
    at com.xmlcalabash.runtime.XPipeline.run(Unknown Source) ~[na:na]
    at org.daisy.common.xproc.calabash.impl.CalabashXProcPipeline.run(CalabashXProcPipeline.java:242) ~[na:na]
    at org.daisy.pipeline.job.Job.run(Job.java:216) ~[na:na]
    at org.daisy.pipeline.job.impl.DefaultJobExecutionService$1.run(DefaultJobExecutionService.java:110) ~[na:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_91]
```

Versions used:

pipeline-assembly @ 921a44fc402fb61b89bb3805ae39143b42fe0d10 (release 1.9.13) + included mod-nlb v1.8.0 for running the job.

...which means for dotify:
- dotify modules:
  - dotify-calabash-2.0.0.jar
  - dotify-core-2.0.1.jar
  - dotify-formatter-1.10.1.jar
  - dotify-saxon-2.1.1.jar
  - dotify-utils-2.0.0.jar
- dotify libraries:
  - org.daisy.dotify.dotify.hyphenator.impl-2.0.1.jar
  - org.daisy.dotify.dotify.api-2.7.0.jar
  - org.daisy.dotify.dotify.formatter.impl-2.3.0.jar
  - org.daisy.dotify.dotify.task.impl-2.4.0.jar
  - org.daisy.dotify.dotify.task-runner-1.0.0.jar
  - org.daisy.dotify.dotify.text.impl-2.0.0.jar
  - org.daisy.dotify.dotify.translator.impl-2.3.0.jar
  - org.daisy.dotify.dotify.common-2.0.2.jar
  - org.daisy.dotify.dotify.task-api-2.1.0.jar

Log and input XML (.txt extension for githubs sake):
- [job-284.txt](https://github.com/joeha480/dotify/files/292946/job-284.txt)
- [552974.xml.txt](https://github.com/joeha480/dotify/files/292957/552974.xml.txt)

**Comment by bertfrees** [comment]
Could you please also attach the OBFL? The DTBook isn't that relevant here. You can produce it with the option "include OBFL".

**Comment by josteinaj** [comment]
Sure.

There's no output file since the job fails, but I can hack it out by enabling calash debug logging in etc/config-logback.xml and adding `<p:identity><p:log port="result"/></p:identity>` in front of dotify:obfl-to-pef inside obfl-to-pef.xpl (it will then output to the console but not the job log).

I've attached the entire job log with debugging enabled, as well as the OBFL part as a separate file. I didn't pretty-print it (in case it matters).

By the way, I'm not sure if it's relevant to dofify, but just in case it is; these two modules do not start due to a restriction in the version of org.daisy.pipeline.braille.common:

```
lb
   47|Installed  |   50|DP2 Braille Modules :: texhyph-utils :: texhyph-saxon (2.0.1)
   77|Installed  |   50|DP2 Braille Modules :: libhyphen-utils :: libhyphen-saxon (2.1.0)
start 47
org.osgi.framework.BundleException: Unresolved constraint in bundle org.daisy.pipeline.modules.braille.texhyph-saxon [47]: Unable to resolve 47.0: missing requirement [47.0] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.braille.common)(version>=4.0.0)(!(version>=5.0.0)))
start 77
org.osgi.framework.BundleException: Unresolved constraint in bundle org.daisy.pipeline.modules.braille.libhyphen-saxon [77]: Unable to resolve 77.0: missing requirement [77.0] osgi.wiring.package; (&(osgi.wiring.package=org.daisy.pipeline.braille.common)(version>=4.0.0)(!(version>=5.0.0)))
```

[job-294.txt](https://github.com/joeha480/dotify/files/293003/job-294.txt)
[obfl.xml.txt](https://github.com/joeha480/dotify/files/293004/obfl.xml.txt)

**Comment by bertfrees** [comment]
Oh, right. Didn't think of that. So in the case of an error the include-obfl options isn't very useful 😞 . We should come up with a solution for that I think. Can we return part of the outputs and still let the job fail?

Anyway, thanks for the OBFL! It looks like there is a bug in css-to-obfl because there is a sequence which tries to use a layout-master called "master_" but it isn't defined. So this isn't a Dotify problem, although it would maybe be better to not throw a NullPointerException.

I didn't notice the issue with the saxon bundles yet but it also doesn't matter that much because those Saxon bindings are used anywhere. But that for letting me know anyway!

**Comment by josteinaj** [comment]
There's no way to provide output files when a job fails since a job failure is a fatal error. Maybe we could use the "VALIDATION_FAIL" status instead.

Is there a quick workaround I can use to get around the NPE for now? I'm getting either this NPE or a "translator not found" (or something) error every time I run a job locally now. I think the translator not found thing is something with how OSGi loads the modules since it only happens half the time, and this NPE seems to be thrown whenever it gets past the translator not found thing. I'll create another issue for the translator not found thing soon, next time I get that error (don't think there's an issue for it?).

**Comment by joeha480** [comment]
This would probably be caught by OBFL validation as the master attribute on sequence is an idref, I think.

**Comment by bertfrees** [comment]
OK.

**Comment by bertfrees** [comment]
@josteinaj Could you try again with the latest master of pipeline-mod-braille? I have fixed a similar issue but I'm not sure it's the same as yours.

**Comment by josteinaj** [comment]
I never got around to trying this it seems.

@bertfrees the changes mentioned here are probably included in the mod-braille that is used in the super-project, right? Which would mean I'm already using them. I tried with the same input DTBook on the most recent nlb-version and there were no errors, so we can probably close this issue...

**Comment by bertfrees** [comment]
See https://github.com/daisy/pipeline-mod-braille/issues/124
